version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: fidelissauro
      POSTGRES_PASSWORD: doutorequemtemdoutorado
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: cosmtrek/air
    container_name: api-posts
    ports:
      - 8080:8080
    working_dir: /api-posts
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_DB=blog
      - DATABASE_USER=fidelissauro
      - DATABASE_PASSWORD=doutorequemtemdoutorado
    volumes:
      - ./:/api-posts
    depends_on:
      - postgres

volumes:
  postgres_data: