// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: imc.proto

package imc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IMCRequest contém o a altura e peso para o qual queremos calcular o IMC.
type IMCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight float64 `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Height float64 `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *IMCRequest) Reset() {
	*x = IMCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMCRequest) ProtoMessage() {}

func (x *IMCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMCRequest.ProtoReflect.Descriptor instead.
func (*IMCRequest) Descriptor() ([]byte, []int) {
	return file_imc_proto_rawDescGZIP(), []int{0}
}

func (x *IMCRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *IMCRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// IMCResponse contém o resultado do cálculo do IMC informado.
type IMCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float64 `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *IMCResponse) Reset() {
	*x = IMCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMCResponse) ProtoMessage() {}

func (x *IMCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMCResponse.ProtoReflect.Descriptor instead.
func (*IMCResponse) Descriptor() ([]byte, []int) {
	return file_imc_proto_rawDescGZIP(), []int{1}
}

func (x *IMCResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_imc_proto protoreflect.FileDescriptor

var file_imc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x69, 0x6d, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x6d, 0x63,
	0x22, 0x3c, 0x0a, 0x0a, 0x49, 0x4d, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x25,
	0x0a, 0x0b, 0x49, 0x4d, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x3d, 0x0a, 0x0a, 0x49, 0x4d, 0x43, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x72, 0x12,
	0x0f, 0x2e, 0x69, 0x6d, 0x63, 0x2e, 0x49, 0x4d, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x69, 0x6d, 0x63, 0x2e, 0x49, 0x4d, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x69, 0x6d, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imc_proto_rawDescOnce sync.Once
	file_imc_proto_rawDescData = file_imc_proto_rawDesc
)

func file_imc_proto_rawDescGZIP() []byte {
	file_imc_proto_rawDescOnce.Do(func() {
		file_imc_proto_rawDescData = protoimpl.X.CompressGZIP(file_imc_proto_rawDescData)
	})
	return file_imc_proto_rawDescData
}

var file_imc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_imc_proto_goTypes = []interface{}{
	(*IMCRequest)(nil),  // 0: imc.IMCRequest
	(*IMCResponse)(nil), // 1: imc.IMCResponse
}
var file_imc_proto_depIdxs = []int32{
	0, // 0: imc.IMCService.Calcular:input_type -> imc.IMCRequest
	1, // 1: imc.IMCService.Calcular:output_type -> imc.IMCResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_imc_proto_init() }
func file_imc_proto_init() {
	if File_imc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imc_proto_goTypes,
		DependencyIndexes: file_imc_proto_depIdxs,
		MessageInfos:      file_imc_proto_msgTypes,
	}.Build()
	File_imc_proto = out.File
	file_imc_proto_rawDesc = nil
	file_imc_proto_goTypes = nil
	file_imc_proto_depIdxs = nil
}
