version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: travels
      POSTGRES_USER: fidelissauro
      POSTGRES_PASSWORD: doutorequemtemdoutorado
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: